language: node_js
node_js:
  - "0.10"
install:
  - npm install -g karma bower gulp
  - bower install
  - npm install
script:
  - node_modules/karma/bin/karma start test/karma.conf.js --single-run --browsers PhantomJS
