language: node_js
node_js:
  - "0.10"
before_install:
  - npm install -g bower
before_script:
  - node_modules/.bin/gulp compile
script:
  - node_modules/karma/bin/karma start test/karma.conf.js --single-run --browsers PhantomJS
